### ISSUE TITLE
Syntaxe Yaml du yaml Editor

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/chaineEditorialeSP#11]
Actuellement, pour les controlledKeywords, YamlEditor produit ceci:
```
controlledKeywords:
  - fr: Espace public
    en: Public space
    it: Spazio pubblico
    url: 'http://catalogue.bnf.fr/ark:/12148/cb12011791z/'
    id: FRBNF12011791
    term: Space
  - fr: Utopie
    en: Utopia
    it: Utopia
    url: 'http://catalogue.bnf.fr/ark:/12148/cb119337395/'
    id: FRBNF11933739
    term:
      - Dystopias
      - Utopias
```

Il faut revenir à la syntaxe initiale : 
```
controlledKeywords:
- label: Didi-Huberman, Georges
  uriRameau: "http://catalogue.bnf.fr/ark:/12148/cb119001364"
  idRameau: FRBNF11900136
  wikidata: "https://www.wikidata.org/wiki/Q1386933" 
```
Lorsqu'il y a du multilingue, la règle est de ne garder que le terme français [fr].
